[package]
name = "meatbag-nudge"
version = "0.4.0"
edition = "2021"

[dependencies]
serde_json = { version = "1", default-features = false, features = ["std"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = "s"
lto = true
strip = true
