[target.x86_64-pc-windows-msvc]
linker = "C:\\Program Files\\Microsoft Visual Studio\\18\\Professional\\VC\\Tools\\MSVC\\14.50.35717\\bin\\Hostx64\\x64\\link.exe"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
